#!/usr/bin/env bash
# generate-config.sh — 扫描 ruleset 生成平台配置
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RULESET_DIR="$PROJECT_ROOT/ruleset"
CONFIG_DIR="$PROJECT_ROOT/configs"
mkdir -p "$CONFIG_DIR"

gen_providers() {
  local header="# Generated by generate-config.sh at $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')"
  echo "$header"
  echo ""
  echo "# ⚙️ rule-providers"
  echo "rule-providers:"
  for f in "$RULESET_DIR"/*.yaml; do
    local name="$(basename "$f" .yaml)"
    local url="https://raw.githubusercontent.com/YOUR_REPO/main/ruleset/${name}.yaml"
    echo "  ${name}:"
    echo "    type: http"
    echo "    behavior: classical"
    echo "    url: \"${url}\""
    echo "    path: ./ruleset/${name}.yaml"
    echo "    interval: 86400"
  done
}

echo "✅ generate-config.sh 占位 — 根据需要完善"